name: Release to Ontology to GitHub Pages
on:
  push:
    tags:
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "zulu"

      - name: Compile ontology modules using rdfx
        run: |
          pip install rdfx
          bash ./tests/build-release.sh

      - name: Provision Widoco
        run: "sudo /bin/sh -c 'wget -O /usr/local/bin/widoco.jar https://github.com/dgarijo/Widoco/releases/download/v1.4.17/java-17-widoco-1.4.17-jar-with-dependencies.jar'"
      - name: Run Widoco
        run: |
          java -jar /usr/local/bin/widoco.jar -ontFile /tmp/ontology/merged.ttl -outFolder tmp/ontology -rewriteAll -webVowl
          mkdir -p release/ontology
          mv tmp/ontology release/ontology/${{ github.ref_name }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          force_orphan: false
          publish_dir: ./release/ontology
          destination_dir: release
          keep_files: true
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
